/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconLineMdAccount: typeof import('~icons/line-md/account.svelte')['default']
  const IconLineMdArrowRightCircle: typeof import('~icons/line-md/arrow-right-circle.svelte')['default']
  const IconLineMdCheckAll: typeof import('~icons/line-md/check-all.svelte')['default']
  const IconLineMdCoffeeHalfEmptyTwotoneLoop: typeof import('~icons/line-md/coffee-half-empty-twotone-loop.svelte')['default']
  const IconLineMdPersonSearch: typeof import('~icons/line-md/person-search.svelte')['default']
  const IconLineMdStarPulsatingFilledLoop: typeof import('~icons/line-md/star-pulsating-filled-loop.svelte')['default']
  const IconLineMdStarPulsatingLoop: typeof import('~icons/line-md/star-pulsating-loop.svelte')['default']
  const IconLineMdStarPulsingLoop: typeof import('~icons/line-md/star-pulsing-loop')['default']
}
